#!/bin/bash
fg="$1"
[ -z "$1" ] && fg="/"

echo "filter: $fg"

for p in "sawtooth" "rand    " "stagger " "plateau " "shuffle " "strings "
do
    echo -en "$p                                          nrec     % speedup     is faster     cmp ratio\n"
    v_print=all
    for l in $log; do echo -en "  $v_print            $l:   \t"; grep "$fg" $l|grep " $(echo $p) "|./stats -; v_print="   "; done
    for v in "ident         " "reverse       " "reverse_front " "reverse_back  " "sorted        " "reverse_sorted" "dither        "
    do
        v_print=$v
        for l in $log; do echo -en "  $v_print $l:   \t"; grep "$fg" $l|grep " $(echo $p) [ ]*$(echo $v) "|./stats -; v_print="              "; done
    done
done
